spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v13?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
dubbo:
  application:
    name: product_service
  registry:
    protocol: zookeeper
    address: 192.168.88.128:2181
  protocol:
    port: 28810
